package Talban.Final;

public class Particle {

    // Basic particle properties
    float x, y;
    float xVelocity, yVelocity;

    // Determines whether or not to remove the particle from the list
    boolean dead;

    // Assigns x and y to the target's x and y
    public Particle(float x, float y) {
        this.x = x;
        this.y = y;
    }

    // Sets the velocities of the particle (should be randomly generated by the Debris parent)
    public void setVelocities(float xVelocity, float yVelocity) {
        this.xVelocity = xVelocity;
        this.yVelocity = yVelocity;
    }

    public void update(float screenHeight) {
        x += xVelocity;
        y += yVelocity;

        // Decrease velocities so that they all aim downwards
        if (xVelocity > 0.5f) {
            xVelocity -= 0.2;
        }
        else if (xVelocity < -0.5f) {
            xVelocity += 0.2;
        }

        yVelocity += 0.5;

        // Toggle dead when the debris is out of screen. Usually not required because the debris dies before.
        if (y > screenHeight) {
            dead = true;
        }
    }

}
